name: Deploy HTML to S3

on: push

jobs:
  deploy-to-s3:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v4
      - name: Configure Aws Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{secrets.AWS_ACCESS_ID}}
          aws-secret-access-key: $ {{secrets.AWS_SECRET_ACCESS_KEY}}
          aws-region: us-east-1
